## We are going to learn Pandas!

In [2]:
import numpy as np
import pandas as pd

In [5]:
## Series function
a=[1,2,3,4,5]
s = pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
# Dictonaries

d={"Name": "marks",
    "Aman":69,
   "Rohan":70,
   "Shubh": 100}

s=pd.Series(d)
print(s)

Name     marks
Aman        69
Rohan       70
Shubh      100
dtype: object

##  Dataframe:

In [12]:
pd.DataFrame({
    "name": ["Aman", "Riya"],
    "salary": [40000, 65000]
})

   name  salary
0  Aman   40000
1  Riya   65000

## Reading from csv file:

In [3]:
df=pd.read_csv("data.csv")
print(df)

# stored in DataFrame df variable
# arr=np.array(fd)
# print(arr)

# value1= arr[:1, 1:]
# print (value1)

     name  age department  salary     city
0    Aman   22         IT   40000    Delhi
1    Riya   24         HR   45000  Lucknow
2   Rahul   23         IT   50000   Indore
3   Priya   25    Finance   55000   Bhopal
4   Karan   21  Marketing   35000   Jaipur
5   Sneha   26         HR   60000   Mumbai
6   Arjun   22    Finance   42000     Pune
7    Neha   24         IT   65000    Delhi
8   Rohit   23  Marketing   38000  Lucknow
9  Ananya   25    Finance   58000   Indore

In [30]:
#Functions in df

#.head() gives first 5 values:
df=pd.read_csv("data.csv")
df.head()

#.tail() gives last 5 values
df.tail()

#gives sample 
df.sample()

#shape
df.shape

#datatypes
df.dtypes

#info
df.info()

#Stats:
df.describe()

#is null?
df.isnull()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     str
 1   age         10 non-null     int64
 2   department  10 non-null     str
 3   salary      10 non-null     int64
 4   city        10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

    name    age  department  salary   city
0  False  False       False   False  False
1  False  False       False   False  False
2  False  False       False   False  False
3  False  False       False   False  False
4  False  False       False   False  False
5  False  False       False   False  False
6  False  False       False   False  False
7  False  False       False   False  False
8  False  False       False   False  False
9  False  False       False   False  False