## Selecting and Filtering:

In [46]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("data.csv")
# print(df)

# selecting single values
# df.salary
# df.department
# df.name
# df.city
# df.age

#altrenate way
# df["age"]
# df["salary"]
# df["department"]

#selecting multiple values(columns)
# df[["salary", "name"]]

#selecting rows
# first make primary index 
df= df.set_index("employee_id")

# access using .loc function
# df.loc[[1,2]]


#slice rows
# df.loc[1:5]
#selecting columns along with rows

# slice
# df.loc[1:5][["name","salary","department"]]

#iloc fn
df.iloc[0:5][["name","salary","department"]]

              name  salary department
employee_id
1             Aman   40000         IT
2             Riya   45000         HR
3            Rahul   50000         IT
4            Priya   55000    Finance
5            Karan   35000  Marketing

## Conditions statements:

In [ ]:
# df["age"]>10
# df.age>10

# df[df["age"]>20]

#departmetnT IT or HR 
# df[(df["department"] == "IT") | (df["department"]== "HR")]


#department IT and age>22
df[(df["department"]=="IT") & (df["age"]>22)]

              name  age department  salary    city
employee_id
3            Rahul   23         IT   50000  Indore
8             Neha   24         IT   65000   Delhi