## Sorting and Ranking:

In [3]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("data.csv")

#Sorting
df.sort_values(by ="employee_id")
df.sort_values(by= "salary")

,employee_id,name,age,department,salary,city,email,joining_date
85,EMP086,Nikhil Bose,43.0,IT,72000,Lucknow,nikhil.bose@company.com,2021-06-14
51,EMP052,Simran Kaur,38.0,HR,-5000,Mumbai,simran.kaur@yahoo.com,2024/07/12
20,EMP021,Yash Thakur,42.0,IT,28000,Delhi,yash.thakur@company.com,2020-11-17
24,EMP025,Ishaan Roy,33.0,Operations,28000,Mumbai,not-an-email,2024/07/12
16,EMP017,Meera Nair,57.0,Marketing,28000,Bhopal,meera.nair@company.com,2024-01-30
...,...,...,...,...,...,...,...,...
43,EMP044,Pooja Mishra,24.0,Finance,95000,Indore,pooja.mishra@company.com,2020-11-17
77,EMP078,Meera Nair,54.0,Marketing,95000,Mumbai,meera.nair@company.com,2020-11-17
30,EMP031,Aisha Khan,56.0,Sales,unknown,Delhi,aisha.khan@company.com,2021-06-14
18,EMP019,Nikhil Bose,32.0,IT,NaN,Lucknow,nikhil.bose@outlook.com,2020-11-17
69,EMP070,Meera Nair,50.0,Finance,NaN,Bhopal,meera.nair@yahoo.com,2022-12-01

In [36]:
## Ranking
df['salary_rank'] = df['salary'].rank(ascending=False)

df = df.sort_values(by='salary_rank')
# print(df)

df['salary']=pd.to_numeric(df['salary'], errors='coerce')
df.nlargest(5,'salary')


df.nsmallest(5,'salary')

,employee_id,name,age,department,salary,city,email,joining_date,salary_rank
51,EMP052,Simran Kaur,38.0,HR,-5000.0,Mumbai,simran.kaur@yahoo.com,2024/07/12,97.0
56,EMP057,Vikram Das,57.0,IT,28000.0,Hyderabad,vikram.das@yahoo.com,2022-12-01,92.5
35,EMP036,Vikram Das,31.0,Finance,28000.0,Lucknow,vikram.das@company.com,2024/07/12,92.5
20,EMP021,Yash Thakur,42.0,IT,28000.0,Delhi,yash.thakur@company.com,2020-11-17,92.5
16,EMP017,Meera Nair,57.0,Marketing,28000.0,Bhopal,meera.nair@company.com,2024-01-30,92.5